# Use root/example as user/password credentials
version: '3.1'

services:

  database:
    image: 'mongo'
    container_name : 'db_paas_cache'
    restart: always
    environment:
        - MONGO_INITDB_DATABASE=db_cache
        - CONFIG_INITDB_ROOT_USERNAME=root
        - CONFIG_INITDB_ROOT_PASSWORD=root
    volumes:
        - ./mongo-volume:/data/db
    ports:
        - '27017-27019:27017-27019'
